# Numpy

In [1]:
import numpy as np  # importing numpy for numerical operations

In [2]:
np.__version__  # checking numpy version

'2.3.4'

In [3]:
import sys  # checking Python version
sys.version

'3.14.0 (tags/v3.14.0:ebf955d, Oct  7 2025, 10:15:03) [MSC v.1944 64 bit (AMD64)]'

# Array creation

In [4]:
l1=[1,2,3,4,5]  # creating a Python list
l1

[1, 2, 3, 4, 5]

In [5]:
type(l1)

list

Create list to array

In [6]:
arr=np.array(l1)    # converting list to numpy array
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

arange function
- The arange function in numpy is used to create arrays with regularly incrementing values.
- It is similar to the built-in range function but returns a numpy array instead of a list. 

    - The syntax for np.arange is as follows: np.arange([start,] stop[, step,], dtype=None)

In [8]:
np.arange(10)   # create array from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(20)   # create array from 0 to 19

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
np.arange(8.0)  # arange function with float argument

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [11]:
np.arange(0,5)  # create array with start index 0 and stop index 4 (n-1)

array([0, 1, 2, 3, 4])

In [12]:
a=np.arange(0,10,2)  # creating values from 0 to 10 with step size 2
a

array([0, 2, 4, 6, 8])

In [13]:
np.arange(10,20)    # Create array from 10 to 19

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
b=np.arange(0,20,3)  # creating values from 0 to 20 with step size 3
b

array([ 0,  3,  6,  9, 12, 15, 18])

In [15]:
np.arange(20,10)    # The first value should be less than the second value

array([], dtype=int64)

In [16]:
np.arange(-20,10)   # -20 is less than 10 so we will get all the sequence from -20 to 10

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.arange(-10,10)   # create array from -10 to 9

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [18]:
np.arange(-20,-10)  # create array from -20 to -11

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [19]:
np.arange(0,-10)        # first value should be less than second value

array([], dtype=int64)

In [20]:
ar=np.arange(0,10)   # we need to provide at least one argument to arange function

In [21]:
ar=np.arange(-30,20)    # create array from -30 to 19
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [22]:
np.arange(10,50,5)      # create array from 10 to 49 with step size 5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
np.arange(-10,10,2)     # create array from -10 to 9 with step size 2

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

In [24]:
np.arange(10,30,2,5)    # arange function takes maximum three arguments: start, stop, step

TypeError: Cannot interpret '5' as a data type

In [25]:
np.arange()   # arange function needs at least one argument

TypeError: arange() requires stop to be specified.

Zero function in numpy
- zeros function is used to create an array filled with zeros
- It takes shape of array as argument
- By default it creates array of float data type
- syntax: np.zeros(shape, dtype=float, order='C')

In [26]:
np.zeros(10)    # create 1D array of zeros with default float datatype

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros(3)     # parameter tuning
# create array of zeros with default float datatype

array([0., 0., 0.])

In [28]:
np.zeros(3, dtype=int)  # hyper parameter tuning
# create 1D array of zeros with integer datatype

array([0, 0, 0])

In [29]:
np.zeros((2,2),dtype=int)   # create 2x2 array of zeros with integer datatype

array([[0, 0],
       [0, 0]])

In [30]:
zero=np.zeros((3,4))   # create 3x4 array of zeros with default float datatype
print(zero)
print(type(zero))   # print type of nd array

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [31]:
np.zeros((10,10), dtype=int)    # create 10x10 array of zeros with integer datatype

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Ones function in numpy
- ones function is used to create an array filled with ones
- It takes shape of array as argument
- By default it creates array of float data type
- syntax : np.ones(shape, dtype=float)

In [32]:
d=np.ones((2,3))    # 2 x 3 array of ones with default float datatype
print("Array d: \n", d)

Array d: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [33]:
e=np.ones((3,2), dtype=int)  # 3 x 2 array of ones with integer datatype
print("Array e: \n", e)

Array e: 
 [[1 1]
 [1 1]
 [1 1]]


In [34]:
np.twos((2,3))    # gives error as there is no function named twos in numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [35]:
np.ones((6,10), dtype=int)    # 6 x 10 array of ones with integer datatype

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

ramdom numbers
- Random numbers are used in simulations and modeling
- They are essential in fields like cryptography, gaming, and statistical sampling
- They provide variability and randomness in data analysis
- random function is required to generate random numbers
- random function is present in random module of numpy library

In [ ]:
rand()   # random numbers

NameError: name 'rand' is not defined

In [37]:
random.rand()   #random module is required to use rand function

NameError: name 'random' is not defined

In [38]:
# random numbers are imported from random module in numPy
import random

In [39]:
np.random.rand()   # generate a random float number between 0.0 to 1.

0.3120509608368831

In [40]:
np.random.rand(5)   # generate 5 random float numbers between 0.0 to 1.

array([0.74635549, 0.43176408, 0.85713139, 0.98492935, 0.75889581])

In [41]:
np.random.rand(3,5)   # generate 3 x 5 array of random float numbers between 0.0 to 1.

array([[0.27865988, 0.3100442 , 0.68170976, 0.10209402, 0.69424767],
       [0.9603743 , 0.57456114, 0.68457794, 0.38006004, 0.31420155],
       [0.79174073, 0.98025785, 0.46789315, 0.2930708 , 0.80327224]])

In [42]:
np.random.randint(3,10)   # generate a random integer between 3 and 9

3

In [43]:
# generate 5 random integers between 1 and 14
#syntax: np.random.randint(low, high=None, size=None, dtype=int)
np.random.randint(1,15,5)   # generate 5 random integers between 1 and 14

array([ 2, 11,  8, 14,  9], dtype=int32)

In [44]:
np.random.randint(20,10,5) # generates error because low > high

ValueError: low >= high

In [45]:
np.random.randint(-20,10,5,2) # gives error because size should be int or tuple of ints

TypeError: Cannot interpret '2' as a data type

In [46]:
np.random.randint(10,50,(4,5))  # generate 4 x 5 array of random integers between 10 and 49

array([[30, 38, 38, 12, 21],
       [35, 15, 16, 47, 16],
       [10, 28, 37, 22, 44],
       [24, 20, 39, 47, 32]], dtype=int32)

In [47]:
np.random.randint(10,100,(10,10))  # generate 10 x 10 array of random integers between 10 and 99

array([[48, 76, 35, 90, 67, 50, 82, 59, 14, 13],
       [71, 69, 48, 61, 43, 43, 30, 73, 44, 46],
       [56, 18, 19, 18, 59, 47, 41, 29, 83, 30],
       [51, 78, 60, 18, 96, 42, 79, 52, 83, 75],
       [58, 58, 51, 82, 79, 80, 24, 90, 16, 29],
       [92, 60, 99, 44, 14, 43, 91, 27, 15, 59],
       [54, 26, 27, 14, 86, 91, 63, 92, 32, 34],
       [44, 10, 63, 75, 18, 86, 74, 65, 19, 12],
       [92, 90, 22, 47, 48, 79, 74, 72, 82, 54],
       [49, 39, 52, 80, 56, 66, 70, 49, 73, 83]], dtype=int32)

In [48]:
arr

array([1, 2, 3, 4, 5])

In [49]:
np.arange(1,15)  # create array from 1 to 14

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Array Manipulations

Reshape
- Reshape function is used to change the shape of an array without changing its data
- It takes a tuple as argument representing the new shape
- syntax : array.reshape(new_shape)

In [50]:
np.arange(1,13).reshape(3,4)  # reshape array to 3 x 4
# The number of elements must match in original and reshaped array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
np.arange(1,13).reshape(6,2)  # reshape array to 6 x 2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [52]:
np.arange(1,15).reshape(3,5)  # This command gives error because 14 elements cannot be reshaped to 3 x 5 (15 elements)

ValueError: cannot reshape array of size 14 into shape (3,5)

In [53]:
a1=np.array([1,2,3,4,5])    # create 1D array from list
reshaped_a1=a1.reshape(5,1)   # reshape array to 5 rows and 1 column
reshaped_a1

array([[1],
       [2],
       [3],
       [4],
       [5]])

Slicing in Matrix
- Slicing is used to access a subset of elements from an array
- It allows us to extract specific rows, columns, or submatrices
- Slicing syntax: array[start:stop:step]

In [54]:
b=np.random.randint(10,30,(6,5))  # generate 6 x 5 array of random integers between 10 and 19
b

array([[28, 16, 12, 28, 21],
       [18, 25, 25, 23, 14],
       [26, 17, 22, 13, 20],
       [10, 27, 25, 11, 16],
       [19, 13, 21, 16, 28],
       [11, 10, 29, 27, 17]], dtype=int32)

In [55]:
b[:] # accessing all elements of the matrix

array([[28, 16, 12, 28, 21],
       [18, 25, 25, 23, 14],
       [26, 17, 22, 13, 20],
       [10, 27, 25, 11, 16],
       [19, 13, 21, 16, 28],
       [11, 10, 29, 27, 17]], dtype=int32)

In [56]:
b[3]  # accessing 4th row of the matrix

array([10, 27, 25, 11, 16], dtype=int32)

In [57]:
b[-4]  # accessing 4th last row of the matrix

array([26, 17, 22, 13, 20], dtype=int32)

In [58]:
b[1,3]  # accessing element at 2nd row and 4th column

np.int32(23)

In [59]:
b[1,2]  # accessing element at 2nd row and 3rd column

np.int32(25)

In [60]:
b[1:2]  # accessing 2nd row of the matrix using slicing

array([[18, 25, 25, 23, 14]], dtype=int32)

In [61]:
b

array([[28, 16, 12, 28, 21],
       [18, 25, 25, 23, 14],
       [26, 17, 22, 13, 20],
       [10, 27, 25, 11, 16],
       [19, 13, 21, 16, 28],
       [11, 10, 29, 27, 17]], dtype=int32)

In [62]:
b[1,-1]  # accessing element at 2nd row and last column

np.int32(14)

In [63]:
b[0:-3]  # accessing all rows except last three rows

array([[28, 16, 12, 28, 21],
       [18, 25, 25, 23, 14],
       [26, 17, 22, 13, 20]], dtype=int32)

In [64]:
b[-5,3]  # accessing element at 5th last row and 4th column

np.int32(23)

In [65]:
b

array([[28, 16, 12, 28, 21],
       [18, 25, 25, 23, 14],
       [26, 17, 22, 13, 20],
       [10, 27, 25, 11, 16],
       [19, 13, 21, 16, 28],
       [11, 10, 29, 27, 17]], dtype=int32)

In [66]:
arr

array([1, 2, 3, 4, 5])

In [67]:
arr[:4]  # accessing first four elements of the array

array([1, 2, 3, 4])

Array Operations

In [68]:
a=np.random.randint(10,20,10)   # create 1D array of 10 random integers between 10 and 29
a

array([14, 18, 13, 12, 17, 16, 18, 17, 11, 18], dtype=int32)

In [69]:
id(a)  # memory address of array a

2867825819152

In [70]:
a1=np.random.randint(0,100,(10,10))   # create 10 x 10 array of random integers between 0 and 99
a1

array([[72, 51, 15, 55, 41, 87, 95, 95, 46, 20],
       [ 5, 15, 89, 63, 90, 43, 51, 35, 25, 39],
       [87, 48, 78, 82, 91, 48, 90, 36, 26, 69],
       [50, 54, 56,  0, 52,  0, 57, 53, 24, 84],
       [73, 68, 79, 67,  5,  6,  2, 36, 75, 23],
       [ 2, 61, 73, 27, 59, 47, 62, 49, 39, 54],
       [46, 26, 12, 34, 58,  5, 95, 39, 38, 14],
       [ 5,  2,  8, 51, 79,  9, 95, 39, 57, 87],
       [10, 19,  8, 84, 47, 89, 95,  9, 17,  0],
       [16, 52, 49, 84, 17,  7,  1, 93, 54, 32]], dtype=int32)

In [71]:
a1[::-1]  # reversing the array rows-wise

array([[16, 52, 49, 84, 17,  7,  1, 93, 54, 32],
       [10, 19,  8, 84, 47, 89, 95,  9, 17,  0],
       [ 5,  2,  8, 51, 79,  9, 95, 39, 57, 87],
       [46, 26, 12, 34, 58,  5, 95, 39, 38, 14],
       [ 2, 61, 73, 27, 59, 47, 62, 49, 39, 54],
       [73, 68, 79, 67,  5,  6,  2, 36, 75, 23],
       [50, 54, 56,  0, 52,  0, 57, 53, 24, 84],
       [87, 48, 78, 82, 91, 48, 90, 36, 26, 69],
       [ 5, 15, 89, 63, 90, 43, 51, 35, 25, 39],
       [72, 51, 15, 55, 41, 87, 95, 95, 46, 20]], dtype=int32)

In [72]:
a1[::-2]  # reversing the array rows-wise with step size 2

array([[16, 52, 49, 84, 17,  7,  1, 93, 54, 32],
       [ 5,  2,  8, 51, 79,  9, 95, 39, 57, 87],
       [ 2, 61, 73, 27, 59, 47, 62, 49, 39, 54],
       [50, 54, 56,  0, 52,  0, 57, 53, 24, 84],
       [ 5, 15, 89, 63, 90, 43, 51, 35, 25, 39]], dtype=int32)

In [73]:
a1[::-3]  # reversing the array rows-wise with step size 3

array([[16, 52, 49, 84, 17,  7,  1, 93, 54, 32],
       [46, 26, 12, 34, 58,  5, 95, 39, 38, 14],
       [50, 54, 56,  0, 52,  0, 57, 53, 24, 84],
       [72, 51, 15, 55, 41, 87, 95, 95, 46, 20]], dtype=int32)

In [74]:
a1

array([[72, 51, 15, 55, 41, 87, 95, 95, 46, 20],
       [ 5, 15, 89, 63, 90, 43, 51, 35, 25, 39],
       [87, 48, 78, 82, 91, 48, 90, 36, 26, 69],
       [50, 54, 56,  0, 52,  0, 57, 53, 24, 84],
       [73, 68, 79, 67,  5,  6,  2, 36, 75, 23],
       [ 2, 61, 73, 27, 59, 47, 62, 49, 39, 54],
       [46, 26, 12, 34, 58,  5, 95, 39, 38, 14],
       [ 5,  2,  8, 51, 79,  9, 95, 39, 57, 87],
       [10, 19,  8, 84, 47, 89, 95,  9, 17,  0],
       [16, 52, 49, 84, 17,  7,  1, 93, 54, 32]], dtype=int32)

In [75]:
a1[:-3]  # accessing all rows except last three rows

array([[72, 51, 15, 55, 41, 87, 95, 95, 46, 20],
       [ 5, 15, 89, 63, 90, 43, 51, 35, 25, 39],
       [87, 48, 78, 82, 91, 48, 90, 36, 26, 69],
       [50, 54, 56,  0, 52,  0, 57, 53, 24, 84],
       [73, 68, 79, 67,  5,  6,  2, 36, 75, 23],
       [ 2, 61, 73, 27, 59, 47, 62, 49, 39, 54],
       [46, 26, 12, 34, 58,  5, 95, 39, 38, 14]], dtype=int32)

In [76]:
a1[0:7:2]  # accessing rows from index 0 to 6 with step size 2

array([[72, 51, 15, 55, 41, 87, 95, 95, 46, 20],
       [87, 48, 78, 82, 91, 48, 90, 36, 26, 69],
       [73, 68, 79, 67,  5,  6,  2, 36, 75, 23],
       [46, 26, 12, 34, 58,  5, 95, 39, 38, 14]], dtype=int32)

In [77]:
a1[1:10:4]   # accessing elements from index 1 to 9 with step size 4

array([[ 5, 15, 89, 63, 90, 43, 51, 35, 25, 39],
       [ 2, 61, 73, 27, 59, 47, 62, 49, 39, 54],
       [16, 52, 49, 84, 17,  7,  1, 93, 54, 32]], dtype=int32)

In [78]:
a

array([14, 18, 13, 12, 17, 16, 18, 17, 11, 18], dtype=int32)

In [79]:
a.min()  # minimum value in the array a

np.int32(11)

In [80]:
a.max()  # maximum value in the array a

np.int32(18)

In [81]:
a.mean()  # mean value of the array a,  formula = sum of elements / number of elements

np.float64(15.4)

In [82]:
a.median()  # median value of the array a, formula = middle value after sorting the elements

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [83]:
from numpy import *  # importing all functions from numpy module
a

array([14, 18, 13, 12, 17, 16, 18, 17, 11, 18], dtype=int32)

In [84]:
median(a)   # median value of the array a, formula = middle value after sorting the elements

np.float64(16.5)

Numpy Indexing
- Indexing always starts with 0
- For 2D array, first index represents row and second index represents column
- Negative indexing starts from the end of the array
- syntax: array_name[row_index, column_index]

In [85]:
mat=np.arange(0,100).reshape(10,10)  # create 10 x 10 matrix with values from 0 to 99
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [86]:
row=5
col=4
mat[row,col]   # access element at row 5, column 4

np.int64(54)

In [87]:
mat[4,5]   # access element at row 4, column 5

np.int64(45)

In [88]:
mat[:]   # access all rows at column 4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [89]:
mat[2]  # access 3rd row of the matrix

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [90]:
mat[:,6]  # access all rows at column 6

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [91]:
mat[:,-1]  # access all rows at last column

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [92]:
mat[:,-2]  # access all rows at second last column

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [93]:
mat[3,:]  # access 4th row of the matrix

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [94]:
mat[:,8]  # access all rows at column 8

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [95]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [96]:
mat[2:6,2:4]  # access rows from index 2 to 5 and columns from index 2 to 3

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [97]:
mat[2:3,2:3]  # access rows from index 2 to 2 and columns from index 2 to 2

array([[22]])

Masking 
- Masking is a technique used to filter data in arrays based on specific conditions
- It creates a boolean array that is then used to index the original array
- The result is an array that contains only the elements that meet the specified condition
- It is useful for data cleaning and preprocessing tasks
- syntax: array[condition]
- Example: array[array > 0] returns all positive elements from the array

In [98]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [99]:
id(mat)  # memory address of matrix mat

2867827860048

In [100]:
mat>50 # checking which elements are greater than 50 in the matrix mat

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [101]:
mat[mat>=50]  # access all elements greater than or equal to 50 in the matrix mat

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [102]:
mat[mat>50]  # access all elements greater than 50 in the matrix mat

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [103]:
mat[mat<20]  # access all elements less than 20 in the matrix mat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [104]:
mat[mat==40]  # access all elements equal to 40 in the matrix mat

array([40])

In [105]:
mat[mat!=40]  # access all elements not equal to 40 in the matrix mat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [114]:
# Identity matrix
# The identity matrix is a square matrix with ones on the diagonal and zeros elsewhere.

f= np.eye(4)   # create identity matrix of size 4x4
print("Identity matrix f: \n", f)

Identity matrix f: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Flatten
- Flattening is the process of converting a multi-dimensional array into a one-dimensional array
- It is useful for simplifying data structures and preparing data for machine learning algorithms
- syntax: array.flatten()
- np.array.ravel() ravel function also flattens the array and is a numpy function

In [107]:
# Flatten array

f1=np.array([[1,2,3],[4,5,6]])  # create 2D array
f1.flatten()   # flatten 2D array to 1D array

array([1, 2, 3, 4, 5, 6])

In [108]:
f1_flattened=np.ravel(f1)   # flatten using ravel()
f1_flattened

array([1, 2, 3, 4, 5, 6])

Transpose
- transpose function is used to interchange rows and columns of an array
- syntax : np.transpose(array)

In [109]:
transposed_f1=f1.T   # transpose the array
print("Transpose Array: \n",transposed_f1)

Transpose Array: 
 [[1 4]
 [2 5]
 [3 6]]


In [110]:
transposed_f1=np.transpose(f1)   # transpose using np.transpose()
print("Transpose Array: \n",transposed_f1)

Transpose Array: 
 [[1 4]
 [2 5]
 [3 6]]


Stack Array
- Stacking is the process of combining multiple arrays into a single array along a specified axis.
- there are two types of stacking: vertical stacking and horizontal stacking.
- Vertical stacking is done using vstack() function, which stacks arrays vertically (row-wise).
- Horizontal stacking is done using hstack() function, which stacks arrays horizontally (column-wise).
- syntax: np.vstack((array1, array2, ...))
- syntax: np.hstack((array1, array2, ...))

In [111]:
# Vertical stacking of arrays prints one array on top of another

a2=np.array([1,2,3,4,5,6])
b2=np.array([7,8,9,10,11,12])
stacked_array=np.vstack([a2,b2])   # vertical stacking of arrays
print("Vertically Stacked Array: \n", stacked_array)

Vertically Stacked Array: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [112]:
# Horizontal stacking of arrays prints two arrays side by side

stacked_array=np.hstack([a2,b2])   # horizontal stacking of arrays
print("Horizontally Stacked Array: \n", stacked_array)


Horizontally Stacked Array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
