# Numpy

- Numpy is a powerful library for numerical computing in Python.
- Numpy provides support for arrays, matrices, and a wide range of mathematical functions.
- Numpy is widely used in data science, machine learning, and scientific computing.
- Numpy is used for data manipulation, analysis, and visualization.
- Numpy is compatible with other popular libraries such as Pandas, Matplotlib, and SciPy.
- Numpy is a fundamental tool for anyone working with data in Python
- Numpy can be installed by:  pip install numpy

- Key Usages of NumPy
    1. Array Creation and Manipulation
        Create arrays using np.array(), np.zeros(), np.ones(), and np.arange().
        Reshape, slice, and index arrays for flexible data handling.

    2. Mathematical Operations
        Perform element-wise operations like addition, subtraction, multiplication, and division.
        Perform element-wise operations like addition, subtraction, multiplication, and division.
        Use built-in functions like np.exp(), np.log(), np.sqrt() for fast computation.

    3. Statistical Analysis
        Compute mean, median, standard deviation, and variance with np.mean(), np.median(), np.std(), np.var().

    4. Linear Algebra
        Matrix multiplication (np.dot()), inversion (np.linalg.inv()), eigenvalues (np.linalg.eig()), and solving systems of equations.

    5. Random Number Generation
        Generate random samples with np.random.rand(), np.random.randint(), and simulate distributions.

    6. Broadcasting
        Apply operations across arrays of different shapes without explicit loops, enabling efficient computation.

    7. Boolean Indexing and Masking
        Filter data using conditions, e.g., arr[arr > 10], for powerful data selection.

    8. Integration with Other Libraries
        NumPy arrays are the foundation for Pandas, SciPy, Scikit-learn, TensorFlow, and more.

    9. Performance Optimization
        NumPy is implemented in C, making it much faster than native Python lists for numerical tasks.

    10. Data Preparation for Machine Learning
        Normalize, reshape, and preprocess data efficiently before feeding it into ML models.

In [1]:
import numpy as np  # importing numpy for numerical operations

In [2]:
np.__version__  # checking numpy version

'2.3.4'

In [3]:
import sys  # checking Python version
sys.version

'3.14.0 (tags/v3.14.0:ebf955d, Oct  7 2025, 10:15:03) [MSC v.1944 64 bit (AMD64)]'

# Array creation

In [4]:
l1=[1,2,3,4,5]  # creating a Python list
l1

[1, 2, 3, 4, 5]

In [5]:
type(l1)

list

Create list to array

In [6]:
arr=np.array(l1)    # converting list to numpy array
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

arange function
- The arange function in numpy is used to create arrays with regularly incrementing values.
- It is similar to the built-in range function but returns a numpy array instead of a list. 

    - The syntax for np.arange is as follows: np.arange([start,] stop[, step,], dtype=None)

In [8]:
np.arange(10)   # create array from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(20)   # create array from 0 to 19

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
np.arange(8.0)  # arange function with float argument

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [11]:
np.arange(0,5)  # create array with start index 0 and stop index 4 (n-1)

array([0, 1, 2, 3, 4])

In [12]:
a=np.arange(0,10,2)  # creating values from 0 to 10 with step size 2
a

array([0, 2, 4, 6, 8])

In [13]:
np.arange(10,20)    # Create array from 10 to 19

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
b=np.arange(0,20,3)  # creating values from 0 to 20 with step size 3
b

array([ 0,  3,  6,  9, 12, 15, 18])

In [15]:
np.arange(20,10)    # The first value should be less than the second value

array([], dtype=int64)

In [16]:
np.arange(-20,10)   # -20 is less than 10 so we will get all the sequence from -20 to 10

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.arange(-10,10)   # create array from -10 to 9

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [18]:
np.arange(-20,-10)  # create array from -20 to -11

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [19]:
np.arange(0,-10)        # first value should be less than second value

array([], dtype=int64)

In [20]:
ar=np.arange(0,10)   # we need to provide at least one argument to arange function

In [21]:
ar=np.arange(-30,20)    # create array from -30 to 19
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [22]:
np.arange(10,50,5)      # create array from 10 to 49 with step size 5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
np.arange(-10,10,2)     # create array from -10 to 9 with step size 2

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

In [24]:
np.arange(10,30,2,5)    # arange function takes maximum three arguments: start, stop, step

TypeError: Cannot interpret '5' as a data type

In [25]:
np.arange()   # arange function needs at least one argument

TypeError: arange() requires stop to be specified.

Zero function in numpy
- zeros function is used to create an array filled with zeros
- It takes shape of array as argument
- syntax: np.zeros(shape, dtype=float, order='C')
    - Shape can be provided as a single integer or tuple of integers
    - dtype is optional argument to specify data type of array, by default it is float and acceptable data types are int, float, complex, bool, etc.
    - order is optional argument to specify whether to store multi-dimensional array in row major(C-style) or column major(Fortran-style) order, by default it is 'C'. order F is used when working with libraries or systems (like Fortran or MATLAB) that expect column-major arrays.
    - Example: 
          -->  np.zeros(5)  # create 1D array of size 5 filled with zeros
    - Example with dtype
          -->  ex: np.zeros((2,3), dtype=int)  # create 2D array of shape 2x3 filled with zeros of integer data type

In [26]:
np.zeros(10)    # create 1D array of zeros with default float datatype

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros(3)     # create array of zeros with default float datatype

array([0., 0., 0.])

In [28]:
np.zeros(3, dtype=int)  # create 1D array of zeros with integer datatype

array([0, 0, 0])

In [29]:
np.zeros((2,2),dtype=int)   # create 2x2 array of zeros with integer datatype, here the shape is provided as tuple

array([[0, 0],
       [0, 0]])

In [30]:
zero=np.zeros((3,4))   # create 3x4 array of zeros with default float datatype
print(zero)
print(type(zero))   # print type of nd array

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [31]:
np.zeros((10,10), dtype=int)    # create 10x10 array of zeros with integer datatype

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Ones function in numpy
- np.ones function is used to create an array filled with ones
- syntax: np.ones(shape, dtype=float, order='C')
     - Shape can be provided as a single integer or tuple of integers
     - dtype is optional argument to specify data type of array, by default it is float and acceptable data types are int, float, complex, bool, etc.
     - order is optional argument to specify whether to store multi-dimensional array in row major(C-style) or column major(F-style)

In [32]:
d=np.ones((2,3))    # 2 x 3 array of ones with default float datatype
print("Array d: \n", d)


Array d: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [33]:
e=np.ones((3,2), dtype=int)  # 3 x 2 array of ones with integer datatype
print("Array e: \n", e)

Array e: 
 [[1 1]
 [1 1]
 [1 1]]


In [35]:
np.twos((2,3))    # gives error as there is no function named twos in numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [36]:
np.ones((6,10), dtype=int)    # 6 x 10 array of ones with integer datatype

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

# Random Sampling
- Random numbers are used in simulations and modeling
- They are essential in fields like cryptography, gaming, and statistical sampling
- They provide variability and randomness in data analysis
- random function is required to generate random numbers and is present in random module of numpy library

In [37]:
random.rand()   #rand function in random module is required to use rand function

NameError: name 'random' is not defined

In [38]:
# we got error because random module is not imported
import random   # import random module

In [39]:
# The rand() function in NumPy is part of the numpy.random module and is used to generate random numbers from a uniform distribution over the interval [0, 1)
# syntax: np.random.rand( d1, d2, ..., dn )

np.random.rand()   # generate a random float number between 0.0 to 1.


0.5511657100554919

In [40]:
np.random.rand(5)   # generate 5 random float numbers between 0.0 to 1.

array([0.63102659, 0.58001314, 0.88357547, 0.84683531, 0.21006463])

In [ ]:
# The seed value acts as a "starting point" for the random number generator; 
# Using the same seed means you get the exact same sequence of random numbers every run, while changing the seed 
# (e.g., from 0 to 1) changes the sequence, making your results reproducible but different from other seeds.​
# Seed 0 will always produce the same sequence for anyone who uses .seed(0).

np.random.seed(0)   # setting seed to 0 for reproducibility
x = np.random.randint(0,10,5)
x

array([5, 0, 3, 3, 7], dtype=int32)

In [49]:
np.random.rand(3,5)   # generate 3 x 5 array of random float numbers between 0.0 to 1.

array([[0.4236548 , 0.64589411, 0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492, 0.56804456, 0.92559664],
       [0.07103606, 0.0871293 , 0.0202184 , 0.83261985, 0.77815675]])

In [50]:
# randint function is used to generate random integers within a specified range
# Returns random integers from low (inclusive) to high (exclusive)
# syntax: np.random.randint(low, high=None, size=None, dtype=int)

np.random.randint(3,10)   # generate a random integer between 3 and 9

3

In [51]:
# generate 5 random integers between 1 and 14
np.random.randint(1,15,5)   # generate 5 random integers between 1 and 14

array([3, 4, 9, 2, 4], dtype=int32)

In [52]:
np.random.seed(0)   # setting seed to 0 for reproducibility
np.random.randint(1,10,5)   # generate 5 random integers between 1 and 9

array([6, 1, 4, 4, 8], dtype=int32)

In [54]:
np.random.randint(20,10,5) # generates error because low > high
# The low value should always be less than the high value

ValueError: low >= high

In [55]:
np.random.randint(-20,10,5,2) # gives error because we have parsed 4 arguments
# size should be int or tuple of ints

TypeError: Cannot interpret '2' as a data type

In [56]:
np.random.randint(10,50,(4,5))  # generate 4 x 5 array of random integers between 10 and 49

array([[19, 29, 31, 46, 33],
       [16, 34, 34, 22, 11],
       [48, 49, 33, 34, 27],
       [47, 35, 23, 18, 19]], dtype=int32)

In [57]:
np.random.randint(10,100,(10,10))  # generate 10 x 10 array of random integers between 10 and 99

array([[30, 90, 79, 89, 57, 74, 92, 98, 59, 39],
       [29, 29, 24, 49, 42, 75, 19, 67, 42, 41],
       [84, 33, 45, 85, 65, 38, 44, 10, 10, 46],
       [63, 15, 48, 27, 89, 14, 52, 68, 41, 11],
       [75, 51, 67, 45, 21, 56, 92, 10, 24, 63],
       [22, 52, 94, 85, 78, 16, 78, 57, 13, 86],
       [62, 88, 25, 30, 68, 33, 89, 23, 95, 58],
       [59, 79, 51, 45, 74, 79, 10, 60, 46, 44],
       [58, 13, 52, 87, 31, 83, 10, 20, 53, 68],
       [33, 69, 12, 72, 45, 77, 92, 56, 30, 91]], dtype=int32)

Linespace
- The linspace function in NumPy is used to create an array of evenly spaced values over a specified range.
- It is particularly useful when you want to generate a sequence of numbers that are evenly distributed between a start and stop value.
- The syntax for the linspace function is as follows:
  - np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    - start: The starting value of the sequence.
    - stop: The end value of the sequence.
    - num: The number of evenly spaced samples to generate (default is 50).
    - endpoint: If True (default), stop is included in the array. If False, the array will not include stop.
    - retstep: If True, return the samples and the step between the samples.
    - dtype: The desired data type for the array. If None, the data type is inferred from the other input arguments.
    - axis: The axis in the result to store the samples. Default is 0.

In [58]:
np.linspace(0,10)   # generate 50 (default number of values) evenly spaced values between 0 and 10

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [59]:
np.linspace(0,10,20)  # creates 20 evenly spaced values between 0 and 10

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

Changing Data Type
- astype() function is used to change the data type of an array
- The supported data types are int, float, complex, bool, str, etc.

In [60]:
# Changing Data Type of Array
x=np.array([11.5, 20.2, 25.6,30.9])
x

array([11.5, 20.2, 25.6, 30.9])

In [61]:
x.astype(int)   # changing float array to integer array

array([11, 20, 25, 30])

# Slicing in Matrix
- Slicing is used to access a subset of elements from an array
- It allows us to extract specific rows, columns, or submatrices
- Slicing syntax: array[start:stop:step]

In [62]:
b=np.random.randint(10,30,(6,5))  # generate 6 x 5 array of random integers between 10 and 30
b

array([[28, 24, 19, 11, 14],
       [20, 21, 18, 21, 12],
       [29, 26, 10, 10, 16],
       [29, 24, 20, 29, 18],
       [23, 12, 13, 12, 21],
       [23, 26, 18, 18, 29]], dtype=int32)

In [63]:
b[:] # accessing all elements of the matrix

array([[28, 24, 19, 11, 14],
       [20, 21, 18, 21, 12],
       [29, 26, 10, 10, 16],
       [29, 24, 20, 29, 18],
       [23, 12, 13, 12, 21],
       [23, 26, 18, 18, 29]], dtype=int32)

In [64]:
b[3]  # accessing 4th row of the matrix

array([29, 24, 20, 29, 18], dtype=int32)

In [65]:
b[-4]  # accessing 4th last row of the matrix

array([29, 26, 10, 10, 16], dtype=int32)

In [66]:
b[1,3]  # accessing element at 2nd row and 4th column

np.int32(21)

In [67]:
b[1,2]  # accessing element at 2nd row and 3rd column

np.int32(18)

In [68]:
b[1:2]  # accessing 2nd row of the matrix using slicing

array([[20, 21, 18, 21, 12]], dtype=int32)

In [69]:
b

array([[28, 24, 19, 11, 14],
       [20, 21, 18, 21, 12],
       [29, 26, 10, 10, 16],
       [29, 24, 20, 29, 18],
       [23, 12, 13, 12, 21],
       [23, 26, 18, 18, 29]], dtype=int32)

In [70]:
b[1,-1]  # accessing element at 2nd row and last column

np.int32(12)

In [71]:
b[0:-3]  # accessing all rows except last three rows

array([[28, 24, 19, 11, 14],
       [20, 21, 18, 21, 12],
       [29, 26, 10, 10, 16]], dtype=int32)

In [72]:
b[-5,3]  # accessing element at 5th last row and 4th column

np.int32(21)

In [73]:
b

array([[28, 24, 19, 11, 14],
       [20, 21, 18, 21, 12],
       [29, 26, 10, 10, 16],
       [29, 24, 20, 29, 18],
       [23, 12, 13, 12, 21],
       [23, 26, 18, 18, 29]], dtype=int32)

In [74]:
arr

array([1, 2, 3, 4, 5])

In [75]:
arr[:4]  # accessing first four elements of the array

array([1, 2, 3, 4])

Array Operations

In [76]:
a=np.random.randint(10,20,10)   # create 1D array of 10 random integers between 10 and 29
a

array([18, 12, 18, 14, 13, 10, 14, 13, 16, 19], dtype=int32)

In [77]:
id(a)  # memory address of array a

1829130008976

In [78]:
a1=np.random.randint(0,100,(10,10))   # create 10 x 10 array of random integers between 0 and 99
a1

array([[75, 56, 16, 24, 29, 21, 25, 80, 60, 61],
       [83, 33, 32, 70, 85, 31, 13, 71, 56, 24],
       [79, 41, 18, 40, 54, 79, 11, 38, 93,  1],
       [95, 44, 88, 24, 67, 82,  3, 76, 35, 86],
       [61, 69, 87, 43, 32, 11, 84, 10, 54, 37],
       [28,  2, 27, 83, 89, 23, 53, 51, 46, 20],
       [53, 29, 67, 35, 39,  9, 73, 41, 23,  3],
       [46, 90, 50,  3, 31,  9, 10, 27, 45, 71],
       [39, 61, 85, 97, 44, 34, 34, 88, 33,  5],
       [36,  0, 75, 34, 69, 53, 80, 62,  8, 61]], dtype=int32)

In [79]:
a1[::-1]  # reversing the array rows-wise

array([[36,  0, 75, 34, 69, 53, 80, 62,  8, 61],
       [39, 61, 85, 97, 44, 34, 34, 88, 33,  5],
       [46, 90, 50,  3, 31,  9, 10, 27, 45, 71],
       [53, 29, 67, 35, 39,  9, 73, 41, 23,  3],
       [28,  2, 27, 83, 89, 23, 53, 51, 46, 20],
       [61, 69, 87, 43, 32, 11, 84, 10, 54, 37],
       [95, 44, 88, 24, 67, 82,  3, 76, 35, 86],
       [79, 41, 18, 40, 54, 79, 11, 38, 93,  1],
       [83, 33, 32, 70, 85, 31, 13, 71, 56, 24],
       [75, 56, 16, 24, 29, 21, 25, 80, 60, 61]], dtype=int32)

In [80]:
a1[::-2]  # reversing the array rows-wise with step size 2

array([[36,  0, 75, 34, 69, 53, 80, 62,  8, 61],
       [46, 90, 50,  3, 31,  9, 10, 27, 45, 71],
       [28,  2, 27, 83, 89, 23, 53, 51, 46, 20],
       [95, 44, 88, 24, 67, 82,  3, 76, 35, 86],
       [83, 33, 32, 70, 85, 31, 13, 71, 56, 24]], dtype=int32)

In [81]:
a1[::-3]  # reversing the array rows-wise with step size 3

array([[36,  0, 75, 34, 69, 53, 80, 62,  8, 61],
       [53, 29, 67, 35, 39,  9, 73, 41, 23,  3],
       [95, 44, 88, 24, 67, 82,  3, 76, 35, 86],
       [75, 56, 16, 24, 29, 21, 25, 80, 60, 61]], dtype=int32)

In [82]:
a1

array([[75, 56, 16, 24, 29, 21, 25, 80, 60, 61],
       [83, 33, 32, 70, 85, 31, 13, 71, 56, 24],
       [79, 41, 18, 40, 54, 79, 11, 38, 93,  1],
       [95, 44, 88, 24, 67, 82,  3, 76, 35, 86],
       [61, 69, 87, 43, 32, 11, 84, 10, 54, 37],
       [28,  2, 27, 83, 89, 23, 53, 51, 46, 20],
       [53, 29, 67, 35, 39,  9, 73, 41, 23,  3],
       [46, 90, 50,  3, 31,  9, 10, 27, 45, 71],
       [39, 61, 85, 97, 44, 34, 34, 88, 33,  5],
       [36,  0, 75, 34, 69, 53, 80, 62,  8, 61]], dtype=int32)

In [83]:
a1[:-3]  # accessing all rows except last three rows

array([[75, 56, 16, 24, 29, 21, 25, 80, 60, 61],
       [83, 33, 32, 70, 85, 31, 13, 71, 56, 24],
       [79, 41, 18, 40, 54, 79, 11, 38, 93,  1],
       [95, 44, 88, 24, 67, 82,  3, 76, 35, 86],
       [61, 69, 87, 43, 32, 11, 84, 10, 54, 37],
       [28,  2, 27, 83, 89, 23, 53, 51, 46, 20],
       [53, 29, 67, 35, 39,  9, 73, 41, 23,  3]], dtype=int32)

In [84]:
a1[0:7:2]  # accessing rows from index 0 to 6 with step size 2

array([[75, 56, 16, 24, 29, 21, 25, 80, 60, 61],
       [79, 41, 18, 40, 54, 79, 11, 38, 93,  1],
       [61, 69, 87, 43, 32, 11, 84, 10, 54, 37],
       [53, 29, 67, 35, 39,  9, 73, 41, 23,  3]], dtype=int32)

In [85]:
a1[1:10:4]   # accessing elements from index 1 to 9 with step size 4

array([[83, 33, 32, 70, 85, 31, 13, 71, 56, 24],
       [28,  2, 27, 83, 89, 23, 53, 51, 46, 20],
       [36,  0, 75, 34, 69, 53, 80, 62,  8, 61]], dtype=int32)

Numpy Indexing
- Indexing always starts with 0
- For 2D array, first index represents row and second index represents column
- Negative indexing starts from the end of the array
- syntax: array_name[row_index, column_index]

In [86]:
mat=np.arange(0,100).reshape(10,10)  # create 10 x 10 matrix with values from 0 to 99
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [87]:
row=5
col=4
mat[row,col]   # access element at row 5, column 4

np.int64(54)

In [88]:
mat[4,5]   # access element at row 4, column 5

np.int64(45)

In [89]:
mat[:]   # access all rows at column 4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [90]:
mat[2]  # access 3rd row of the matrix

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [91]:
mat[:,6]  # access all rows at column 6

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [92]:
mat[:,-1]  # access all rows at last column

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [93]:
mat[:,-2]  # access all rows at second last column

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [94]:
mat[3,:]  # access 4th row of the matrix

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [95]:
mat[:,8]  # access all rows at column 8

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [96]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [97]:
mat[2:6,2:4]  # access rows from index 2 to 5 and columns from index 2 to 3

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [98]:
mat[2:3,2:3]  # access rows from index 2 to 2 and columns from index 2 to 2

array([[22]])

Masking 
- Masking is a technique used to filter data in arrays based on specific conditions
- It creates a boolean array that is then used to index the original array
- The result is an array that contains only the elements that meet the specified condition
- It is useful for data cleaning and preprocessing tasks
- syntax: array[condition]
- Example: array[array > 0] returns all positive elements from the array

In [99]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [100]:
id(mat)  # memory address of matrix mat

1829130436752

In [101]:
mat>50 # checking which elements are greater than 50 in the matrix mat

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [102]:
mat[mat>=50]  # access all elements greater than or equal to 50 in the matrix mat

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [103]:
mat[mat>50]  # access all elements greater than 50 in the matrix mat

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [104]:
mat[mat<20]  # access all elements less than 20 in the matrix mat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [105]:
mat[mat==40]  # access all elements equal to 40 in the matrix mat

array([40])

In [106]:
mat[mat!=40]  # access all elements not equal to 40 in the matrix mat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Identity matrix
- The identity matrix is a square matrix with ones on the diagonal and zeros elsewhere.

In [107]:
f= np.eye(4)   # create identity matrix of size 4x4
print("Identity matrix f: \n", f)

Identity matrix f: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Manipulations

Reshape
- Reshape function is used to change the shape of an array without changing its data
- It takes a tuple as argument representing the new shape
- syntax : array.reshape(new_shape)

In [108]:
np.arange(1,13) # generate array from 1 to 12

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [109]:
np.arange(1,13).reshape(3,4)  # reshape array to 3 x 4
# The number of elements must match in original and reshaped array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [110]:
np.arange(1,13).reshape(3,4)  # reshape array to 3 x 4
# The number of elements must match in original and reshaped array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [111]:
np.arange(1,13).reshape(6,2)  # reshape array to 6 x 2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [113]:
np.arange(1,15).reshape(3,5)  # Gives error because 14 elements cannot be reshaped to 3 x 5 (15 elements)

ValueError: cannot reshape array of size 14 into shape (3,5)

In [114]:
a1=np.array([1,2,3,4,5])    # create 1D array from list
reshaped_a1=a1.reshape(5,1)   # reshape array to 5 rows and 1 column
reshaped_a1

array([[1],
       [2],
       [3],
       [4],
       [5]])

Flatten
- Flattening is the process of converting a multi-dimensional array into a one-dimensional array
- It is useful for simplifying data structures and preparing data for machine learning algorithms
- syntax: array.flatten()
- np.array.ravel() ravel function also flattens the array and is a numpy function

In [115]:
# Flatten array

f1=np.array([[1,2,3],[4,5,6]])  # create 2D array
f1.flatten()   # flatten 2D array to 1D array

array([1, 2, 3, 4, 5, 6])

In [116]:
f1=np.array([[7,8,9],[10,11,12],[13,14,15],[16,17,18]])  # create 4D array
f1

array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [117]:
f1_flattened=np.ravel(f1)   # flatten using ravel()
f1_flattened

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

Transpose
- transpose function is used to interchange rows and columns of an array
- syntax : np.transpose(array)

In [118]:
transposed_f1=f1.T   # .T attribute is used to transpose the array
print("Transpose Array: \n",transposed_f1)

Transpose Array: 
 [[ 7 10 13 16]
 [ 8 11 14 17]
 [ 9 12 15 18]]


In [119]:
transposed_f1=np.transpose(f1)   # transpose using np.transpose()
print("Transpose Array: \n",transposed_f1)

Transpose Array: 
 [[ 7 10 13 16]
 [ 8 11 14 17]
 [ 9 12 15 18]]


Stack Array
- Stacking is the process of combining multiple arrays into a single array along a specified axis.
- there are two types of stacking: vertical stacking and horizontal stacking.
- Vertical stacking is done using vstack() function, which stacks arrays vertically (row-wise).
- Horizontal stacking is done using hstack() function, which stacks arrays horizontally (column-wise).
- syntax: np.vstack((array1, array2, ...))
- syntax: np.hstack((array1, array2, ...))

In [120]:
# Vertical stacking of arrays prints one array on top of another

a2=np.array([1,2,3,4,5,6])
b2=np.array([7,8,9,10,11,12])
stacked_array=np.vstack([a2,b2])   # vertical stacking of arrays
print("Vertically Stacked Array: \n", stacked_array)

Vertically Stacked Array: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [121]:
# Horizontal stacking of arrays prints two arrays side by side

stacked_array=np.hstack([a2,b2])   # horizontal stacking of arrays
print("Horizontally Stacked Array: \n", stacked_array)


Horizontally Stacked Array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


# Mathematical Functions

add
- add function is used to add two arrays element-wise or add a constant value to each element of the array


In [122]:
m1 = np.array([1, 2, 3, 4])
added = np.add(m1, 2)  # Add 2 to each element
print("Added 2 to m1:", added)

Added 2 to m1: [3 4 5 6]


In [123]:
# Add two arrays element-wise
m1 = np.array([1, 2, 3, 4]) 
m2 = np.array([5, 6, 7, 8])
added = np.add(m1, m2)  # Add two arrays element-wise
print("Element-wise addition of m1 and m2:", added)

Element-wise addition of m1 and m2: [ 6  8 10 12]


power
- Power function is used to raise each element of the array to the specified exponent

In [124]:
squared = np.power(m1, 2)  # Square each element of m1
print("Squared m1:", squared)

Squared m1: [ 1  4  9 16]


In [125]:
cubed = np.power(m1, 3)  # Cube each element of m1
print("Cubed m1:", cubed)

Cubed m1: [ 1  8 27 64]


Square root
- sqrt function is used to compute the square root of each element in the array

In [126]:
m3=np.array([2,4,8,9,16])
sqrt_m3 = np.sqrt(m3)  # Compute the square root of each element in m3
print("Square root of m3:", sqrt_m3)    

Square root of m3: [1.41421356 2.         2.82842712 3.         4.        ]


Dot product
- Dot product of two arrays is calculated using np.dot() function
- dot product multiplies corresponding elements and then sums them up

In [127]:
print(m1)
print(m2)

[1 2 3 4]
[5 6 7 8]


In [128]:
dot_product = np.dot(m1, m2)  # Compute the dot product of m1 and m2
print("Dot product of m1 and m2:", dot_product)

Dot product of m1 and m2: 70


# Statistical Functions

In [129]:
# mean is the average of the elements in the array
# formula: mean = sum of elements / number of elements

s=np.array([1,2,3,4,5])
mean_s = np.mean(s)  # Calculate the mean of the array s
print("Mean of s:", mean_s)

Mean of s: 3.0


In [130]:
# Standard Deviation
# Standard deviation measures the amount of variation or dispersion in a set of values.
# formula: std = sqrt(sum((x - mean)^2) / N)
# where x is each value, mean is the average, and N is the number of values
std_s = np.std(s)  # Calculate the standard deviation of the array s
print("Standard Deviation of s:", std_s)

Standard Deviation of s: 1.4142135623730951


In [131]:
# minimum value in the array
# min = the smallest element in the array
min_s = np.min(s)  # Calculate the minimum value of the array s
print("Minimum of s:", min_s)

Minimum of s: 1


In [132]:
# maximum value in the array
# max = the largest element in the array
max_s = np.max(s)  # Calculate the maximum value of the array s
print("Maximum of s:", max_s)   

Maximum of s: 5


# Boolean & Logical Operations
- Boolean and Logical Operations are used to perform operations based on conditions
- They return boolean arrays indicating whether each element meets the condition
- syntax: np.logical_and(condition1, condition2), np.logical_or(condition1, condition2), np.logical_not(condition)


In [133]:
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [134]:
a = np.array([True, False, True])
b = np.array([False, False, True])

In [135]:
# Logical AND
np.logical_and(a, b)

array([False, False,  True])

In [136]:
# Logical OR
np.logical_or(a, b) 

array([ True, False,  True])

In [137]:
# Logical NOT
np.logical_not(a) 

array([False,  True, False])

In [138]:
# Logical XOR
np.logical_xor(a, b)

array([ True, False, False])

In [139]:
x = np.array([1, 2, 3, 4])

In [140]:
# Greater than
x > 2

array([False, False,  True,  True])

In [141]:
# Equal to
x == 3

array([False, False,  True, False])

In [142]:
# Combine conditions
np.logical_and(x > 1, x < 4)

array([False,  True,  True, False])

- np.any(condition) – Returns True if any element is True
- np.all(condition) – Returns True if all elements are True
- np.where(condition, x, y) – Element-wise selection based on condition

In [143]:
x = np.array([1, 2, 3, 4])
np.where(x > 2, x, -1)  # Where condition returns elements from x where condition is True, else returns -1
# Syntax: np.where(condition, x, y) – Element-wise selection based on condition


array([-1, -1,  3,  4])

In [144]:
# Conditional Masking
x = np.array([10, 20, 30, 40])

# Select elements greater than 25
mask = x > 25
x[mask]

array([30, 40])

In [145]:
# Combine multiple conditions
x[np.logical_or(x < 15, x > 35)]

array([10, 40])

# Set operations 


In [146]:
a = np.array([1, 2, 2, 3, 4, 4])
np.unique(a)    # unique function returns the sorted unique elements of an array

array([1, 2, 3, 4])

In [147]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

In [148]:
# Intersection function is used to find common elements between two arrays
intersection = np.intersect1d(a, b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [149]:
# Union function is used to find all unique elements from both arrays
union = np.union1d(a, b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


In [150]:
# Set difference function is used to find elements in one array that are not in another array
np.setdiff1d(a, b)  # Elements in a not in b

array([1, 2])

In [151]:
# Xor function is used to find elements that are in either of the arrays but not in both
np.setxor1d(a, b)  # Elements in a or b but not in both

array([1, 2, 5, 6])

In [152]:
# in1d function is used to test whether elements of one array are present in another array
np.isin([1, 2, 5], [2, 3, 4])   

array([False,  True, False])

Array Attribute Functions:
- shape: returns the dimensions of the array    
- dtype: returns the data type of the array
- ndim: returns the number of dimensions of the array
- size: returns the total number of elements in the array
- itemsize: returns the size (in bytes) of each element in the array

In [153]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array
itemsize= a.itemsize  # Size of each element in bytes

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)
print("Item size of a:", itemsize)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64
Item size of a: 8


Broadcasting
- Broadcasting allows numpy to perform Arithmetic operations on arrays of different shapes without explicitly reshaping them.
- It works by "stretching" the smaller array across the larger array so that they have compatible shapes for element-wise operations.\

In [154]:
# Adding a scalar to an array using broadcasting

a = np.array([1, 2, 3])
b = 5

result = a + b
print(result)

[6 7 8]


In [155]:
# Adding 1D array and 2D array using broadcasting

a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

result = a + b
print(result)

[[11 22 33]
 [14 25 36]]


In [156]:
# Broadcasting example with column vector and row vector

a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])

result = a + b
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [157]:
# Multiplying different shaped arrays using broadcasting

a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[2],
              [3]])

result = a * b
print(result)

[[ 2  4  6]
 [12 15 18]]


Other Functions

In [158]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [159]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [160]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
